export const DELETE_VALUE = "DELETE_VALUE";
export const VALUE_CHANGED = "VALUE_CHANGED";

export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";
